name: Prettier for TS Code

on:
  push:
    branches: [master]

jobs:
  cleanup_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1 # history might get messy
    - name: Prettify the TS Code
      uses: blatayue/prettier_action@0.2-alpha
      with:
        prettier_options: "--write src/**/*.ts"
        branch: master
        dry: true  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
