name: Prettier for TS Code

on:
  push:
    branches: [master]

jobs:
  cleanup_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1 # history might get messy
    - name: Prettify the TS Code
      uses: creyD/prettier_action@v2.1
      with:
        prettier_options: --write src/**/*.ts
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Pushing back to master
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
