name: Prettier for TS Code

on:
  push:
    branches: [master]

jobs:
  make_pretty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: run prettier on src folder
    - run: npx prettier --write "src/**/*.ts"
    - name: Pushing back to master
      uses: mikeal/publish-to-github-action@master 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
